from pydantic import BaseModel, Field
from enum import Enum
from typing import Optional
from datetime import datetime


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class AttackType(str, Enum):
    PROMPT_INJECTION = "prompt_injection"
    TOOL_MANIPULATION = "tool_manipulation"
    DATA_EXFILTRATION = "data_exfiltration"
    PROMPT_EXTRACTION = "prompt_extraction"
    REASONING_HIJACK = "reasoning_hijack"


class OWASPCategory(str, Enum):
    LLM01 = "LLM01: Prompt Injection"
    LLM02 = "LLM02: Insecure Output Handling"
    LLM06 = "LLM06: Sensitive Information Disclosure"
    LLM07 = "LLM07: Insecure Plugin Design"
    LLM09 = "LLM09: Overreliance"


class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class AttackOutcome(str, Enum):
    SUCCESS = "success"    # Attack fully achieved its goal
    PARTIAL = "partial"    # Attack partially succeeded
    BLOCKED = "blocked"    # Defense layer caught it
    FAILED = "failed"      # Attack didn't work


# ---------------------------------------------------------------------------
# Core Models
# ---------------------------------------------------------------------------

class ToolInfo(BaseModel):
    """A tool discovered during recon."""
    name: str
    description: str
    parameters: dict
    observed_behavior: str


class TargetProfile(BaseModel):
    """Output of the Recon Agent. Describes everything known about the target."""
    tools: list[ToolInfo]
    data_sources: list[str]
    system_prompt_leaked: Optional[str] = None
    guardrails_detected: list[str]
    attack_surface_notes: str
    raw_recon_conversation: list[dict]


class AttackPayload(BaseModel):
    """A single attack attempt generated by an attack strategy."""
    attack_type: AttackType
    strategy_name: str
    description: str
    messages: list[dict]        # [{"role": "user", "content": "..."}]
    injected_content: Optional[str] = None
    target_tool: Optional[str] = None


class AttackResult(BaseModel):
    """Output of the Evaluator Agent for a single attack attempt."""
    payload: AttackPayload
    outcome: AttackOutcome
    owasp_category: OWASPCategory
    severity: Severity
    severity_score: float       # 0.0 - 10.0 (CVSS-like)
    evidence: str
    target_response: str
    data_compromised: Optional[str] = None
    defense_triggered: bool = False
    timestamp: datetime = Field(default_factory=datetime.utcnow) 


class ScanResult(BaseModel):
    """Complete output of a full AgentProbe scan."""
    target_profile: TargetProfile
    attack_results: list[AttackResult]
    total_attacks: int
    successful_attacks: int
    blocked_attacks: int
    attack_success_rate: float                  # Without defense
    attack_success_rate_with_defense: float     # With defense active
    classifier_metrics: Optional[dict] = None   # {"precision": ..., "recall": ..., "f1": ...}
    owasp_coverage: dict[str, int]              # category -> count of findings
    scan_duration_seconds: float
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class VulnerabilityFinding(BaseModel):
    """A single finding in the final report, derived from AttackResult."""
    id: str                         # e.g., "VULN-001"
    title: str
    owasp_category: OWASPCategory
    severity: Severity
    severity_score: float
    description: str
    reproduction_steps: list[str]
    evidence: str
    remediation: str
    attack_type: AttackType


class VulnerabilityReport(BaseModel):
    """The final structured report."""
    executive_summary: str
    risk_score: float               # Aggregate 0-10
    findings: list[VulnerabilityFinding]
    owasp_heatmap: dict[str, int]   # category -> count
    defense_effectiveness: dict     # before/after metrics
    scan_metadata: dict             # duration, timestamp, target info
